languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "xinyixia.com"
canonifyurls = true
title = "Xinyi"
author = "xinyixia"
theme = "pixyll"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  #google_analytics_id = "XX-XXXXXXXX-X"
  #twitter_username = "username"
  #paginate = true
